"""
count_figures.py

Counts the number of figures in each XML article generated by Grobid.

Figures are identified through elements of the form:
<figure xml:id="fig_X">

where X is a number.

The script avoids counting figure references (e.g., target="#fig_0")
and only counts actual figure definitions.

Output:
results/figures_per_article.png
"""

import os
import re
from lxml import etree
import matplotlib.pyplot as plt

XML_DIR = "../data/grobid_xmls"
OUTPUT_FILE = "../results/figures_per_article.png"

TEI_NS = {"tei": "http://www.tei-c.org/ns/1.0"}

FIG_PATTERN = r"fig_\d+"


def count_figures():

    articles = []
    counts = []

    for file in os.listdir(XML_DIR):

        if not file.endswith(".xml"):
            continue

        filepath = os.path.join(XML_DIR, file)

        tree = etree.parse(filepath)

        figures = tree.xpath("//tei:figure", namespaces=TEI_NS)

        figure_ids = set()

        for fig in figures:

            fig_id = fig.get("{http://www.w3.org/XML/1998/namespace}id")

            if fig_id and re.match(FIG_PATTERN, fig_id):

                figure_ids.add(fig_id)

        articles.append(file.replace(".xml",""))
        counts.append(len(figure_ids))

    return articles, counts


def plot_figures(articles, counts):

    plt.figure(figsize=(10,6))

    bars = plt.bar(articles, counts)

    plt.xlabel("Article")
    plt.ylabel("Number of Figures")
    plt.title("Number of Figures per Article")

    plt.xticks(rotation=45)

    for bar in bars:

        height = bar.get_height()

        plt.text(
            bar.get_x() + bar.get_width()/2,
            height,
            str(height),
            ha='center',
            va='bottom'
        )

    plt.tight_layout()

    plt.savefig(OUTPUT_FILE)

    print("Chart saved in:", OUTPUT_FILE)


def main():

    articles, counts = count_figures()

    plot_figures(articles, counts)


if __name__ == "__main__":
    main()
