"""
extract_links.py

Extracts links from TEI XML files generated by Grobid.

Detected patterns:
1) <ref type="url" target="...">
2) URLs appearing as text inside <p> elements (e.g., footnotes)
3) <ptr target="..."> used in bibliographic references

The script does NOT remove duplicates.

Output:
results/links_per_article.csv
Format:
article;link
"""

import os
import re
import pandas as pd
from lxml import etree

XML_DIR = "data/grobid_xmls"
OUTPUT_FILE = "results/links_per_article.csv"

TEI_NS = {"tei": "http://www.tei-c.org/ns/1.0"}

URL_PATTERN = r"https?://[^\s<>\"']+"


def extract_links():

    rows = []

    for file in os.listdir(XML_DIR):

        if not file.endswith(".xml"):
            continue

        filepath = os.path.join(XML_DIR, file)
        tree = etree.parse(filepath)

        refs = tree.xpath(
            "//tei:ref[@type='url']",
            namespaces=TEI_NS
        )

        for ref in refs:

            link = ref.get("target")

            if link and link.startswith(("http://", "https://")):

                rows.append({
                    "article": file,
                    "link": link
                })

        paragraphs = tree.xpath(
            "//tei:p//text()",
            namespaces=TEI_NS
        )

        for text in paragraphs:

            urls = re.findall(URL_PATTERN, text)

            for link in urls:

                link = link.rstrip(".,);]")

                rows.append({
                    "article": file,
                    "link": link
                })

        ptrs = tree.xpath(
            "//tei:ptr[@target]",
            namespaces=TEI_NS
        )

        for ptr in ptrs:

            link = ptr.get("target")

            if link and link.startswith(("http://", "https://")):

                rows.append({
                    "article": file,
                    "link": link
                })

    return pd.DataFrame(rows)


def main():

    df = extract_links()

    df.to_csv(
        OUTPUT_FILE,
        sep=";",
        index=False
    )

    print("Files saved in:", OUTPUT_FILE)
    print("Total links found:", len(df))


if __name__ == "__main__":
    main()
